import { defineConfig } from 'tsup'

export default defineConfig({
  // One entry per public subpath, so `exports` can point each consumer at a
  // self-contained module. `splitting: false` keeps each entry standalone;
  // shared React/Radix/Phosphor modules stay external (peer/regular deps).
  entry: {
    index: 'src/index.ts',
    'canvas/index': 'src/canvas/index.ts',
    'layouts/index': 'src/layouts/index.ts',
    'layouts/band': 'src/layouts/band.ts',
    registry: 'src/registry.ts',
    types: 'src/types.ts',
    theme: 'src/theme.ts',
    layout: 'src/layout.ts',
    examples: 'src/examples.ts',
    'showcase/index': 'src/showcase/index.ts',
  },
  format: ['esm'],
  dts: true,
  outDir: 'dist',
  // Keep dist/styles.css (generated by build:css) intact.
  clean: false,
  splitting: false,
  sourcemap: false,
  external: [
    'react',
    'react-dom',
    'react/jsx-runtime',
    'react-dom/server',
    '@phosphor-icons/react',
    '@radix-ui/react-tooltip',
    'clsx',
    'tailwind-merge',
  ],
  outExtension: () => ({ js: '.js' }),
})
