import { test, expect } from '@playwright/test'

test('T16.1 IME composition never commits intermediate text and applies once on confirm', async ({
  page,
}) => {
  await page.goto('/studio.html')
  const node = page.getByRole('button', { name: 'Order API', exact: true })
  await node.click()
  const label = page.getByLabel('Label', { exact: true })
  await label.focus()
  await label.fill('')
  const undo = page.getByRole('button', { name: 'Undo', exact: true })
  await expect(undo).toBeDisabled()
  const cdp = await page.context().newCDPSession(page)
  await cdp.send('Input.imeSetComposition', { text: 'α', selectionStart: 1, selectionEnd: 1 })
  await cdp.send('Input.imeSetComposition', { text: 'αβ', selectionStart: 2, selectionEnd: 2 })
  await expect(undo).toBeDisabled()
  await expect(node).toHaveAttribute('aria-pressed', 'true')
  await cdp.send('Input.insertText', { text: 'αβ' })
  await cdp.detach()
  await page.getByRole('button', { name: 'Apply label', exact: true }).click()
  await expect(page.getByRole('button', { name: 'αβ', exact: true })).toBeVisible()
  await expect(undo).toBeEnabled()
  await undo.click()
  await expect(page.getByRole('button', { name: 'Order API', exact: true })).toBeVisible()
  await expect(undo).toBeDisabled()
})

test('T16.1 composition left unconfirmed persists nothing', async ({ page }) => {
  await page.goto('/studio.html')
  const node = page.getByRole('button', { name: 'Order API', exact: true })
  await node.click()
  const label = page.getByLabel('Label', { exact: true })
  await label.focus()
  await label.fill('')
  const cdp = await page.context().newCDPSession(page)
  await cdp.send('Input.imeSetComposition', { text: 'γδ', selectionStart: 2, selectionEnd: 2 })
  await cdp.send('Input.insertText', { text: 'γδ' })
  await cdp.detach()
  await page.getByRole('button', { name: 'Pan', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Order API', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeDisabled()
  await expect(page.getByText('No pending changes', { exact: true })).toBeVisible()
})

test('T16.1 labels stay literal text without executing markup', async ({ page }) => {
  await page.goto('/studio.html')
  const node = page.getByRole('button', { name: 'Order API', exact: true })
  await node.click()
  const label = page.getByLabel('Label', { exact: true })
  await label.focus()
  await label.fill('')
  const cdp = await page.context().newCDPSession(page)
  await cdp.send('Input.insertText', { text: '<b onclick="alert(1)">X</b>' })
  await cdp.detach()
  await page.getByRole('button', { name: 'Apply label', exact: true }).click()
  const literal = page.getByRole('button', { name: '<b onclick="alert(1)">X</b>', exact: true })
  await expect(literal).toBeVisible()
  expect(await page.locator('svg b').count()).toBe(0)
  expect(await page.locator('[onclick]').count()).toBe(0)
  const dialogs: string[] = []
  page.on('dialog', async (dialog) => {
    dialogs.push(dialog.message())
    await dialog.dismiss()
  })
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Order API', exact: true })).toBeVisible()
  expect(dialogs).toEqual([])
})

test('T16.1 the JSON draft stays uncommitted while text is composed', async ({ page }) => {
  await page.goto('/studio.html')
  await page.getByText('Document JSON', { exact: true }).click()
  const json = page.getByRole('textbox', { name: 'Document JSON' })
  await json.focus()
  const undo = page.getByRole('button', { name: 'Undo', exact: true })
  await expect(undo).toBeDisabled()
  const cdp = await page.context().newCDPSession(page)
  await cdp.send('Input.imeSetComposition', { text: 'abc', selectionStart: 3, selectionEnd: 3 })
  await expect(undo).toBeDisabled()
  await cdp.send('Input.insertText', { text: 'abc' })
  await cdp.detach()
  await expect(undo).toBeDisabled()
  await page.getByRole('button', { name: 'Discard draft', exact: true }).click()
  await expect(undo).toBeDisabled()
  await expect(page.getByText('No pending changes', { exact: true })).toBeVisible()
})
