import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createGenerator } from 'ts-json-schema-generator'
import Ajv from 'ajv'
import standaloneCode from 'ajv/dist/standalone/index.js'

const generator = createGenerator({
  path: 'src/types.ts',
  type: '*',
  tsconfig: 'tsconfig.json',
  additionalProperties: false,
  skipTypeCheck: false,
})
const names = [
  'DiagramSpec',
  'BandDiagramSpec',
  'FlowchartDiagramSpec',
  'SequenceDiagramSpec',
  'StateMachineDiagramSpec',
  'ErDiagramSpec',
  'TimelineDiagramSpec',
  'SwimlaneDiagramSpec',
  'GraphDiagramSpec',
  'DiagramDocument',
  'DiagramFragment',
]
const check = process.argv.includes('--check')
function output(path, value) {
  if (check) {
    if (readFileSync(path, 'utf8') !== value) throw new Error(`Generated contract drift: ${path}`)
  } else writeFileSync(path, value)
}
mkdirSync('schemas', { recursive: true })
mkdirSync('src/validation', { recursive: true })
for (const name of names) {
  const schema = generator.createSchema(name)
  output(`schemas/${name}.schema.json`, JSON.stringify(schema, null, 2) + '\n')
  const validators = {
    DiagramSpec: 'structural',
    GraphDiagramSpec: 'graph-structural',
    DiagramDocument: 'document-structural',
    DiagramFragment: 'fragment-structural',
  }
  if (name in validators) {
    const ajv = new Ajv({ allErrors: true, strict: false, code: { source: true, esm: true } })
    const validate = ajv.compile(schema)
    output(
      `src/validation/${validators[name]}.js`,
      '// Generated by scripts/generate-schemas.mjs; do not edit.\n' +
        standaloneCode(ajv, validate) +
        '\n',
    )
  }
}
console.log(
  check
    ? 'Schemas and standalone validator are in sync'
    : 'Generated schemas and standalone validators from TypeScript',
)
