import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'
import { minimalSpecs } from '../examples/specs'
import { usageSnippet } from '../site/src/lib/code'
import { validateDiagramSpec } from '../src/validation'
const manifest = JSON.parse(readFileSync('package.json', 'utf8'))
const check = process.argv.includes('--check')
function output(path: string, value: string) {
  if (check) {
    if (readFileSync(path, 'utf8') !== value) throw new Error(`Documentation drift: ${path}`)
  } else {
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, value)
  }
}
const titles: Record<string, string> = {
  band: 'Band',
  flowchart: 'Flowchart',
  sequence: 'Sequence',
  'state-machine': 'State machine',
  er: 'Entity relationship',
  timeline: 'Timeline',
  swimlane: 'Swimlane',
}
const types: Record<string, string> = {
  band: 'BandDiagramSpec',
  flowchart: 'FlowchartDiagramSpec',
  sequence: 'SequenceDiagramSpec',
  'state-machine': 'StateMachineDiagramSpec',
  er: 'ErDiagramSpec',
  timeline: 'TimelineDiagramSpec',
  swimlane: 'SwimlaneDiagramSpec',
}
for (const [type, spec] of Object.entries(minimalSpecs)) {
  const result = validateDiagramSpec(spec)
  if (!result.success) throw new Error(JSON.stringify(result.issues))
  const json = JSON.stringify(spec, null, 2) + '\n'
  output(`examples/${type}.json`, json)
  output(`examples/${type}.tsx`, usageSnippet(`example-${type}`, type, spec))
  const schema = JSON.parse(readFileSync(`schemas/${types[type]}.schema.json`, 'utf8'))
  const definitions = schema.definitions as Record<
    string,
    { properties?: Record<string, unknown>; required?: string[]; description?: string }
  >
  let fields = ''
  for (const [name, definition] of Object.entries(definitions)) {
    if (!definition.properties) continue
    fields += `\n## ${name}\n\n| Field | Required | Contract |\n|---|---|---|\n`
    for (const [key, property] of Object.entries(definition.properties)) {
      const field = property as Record<string, unknown>
      fields += `| \`${key}\` | ${definition.required?.includes(key) ? 'yes' : 'no'} | ${String(
        field.description ?? JSON.stringify(field),
      )
        .replaceAll('|', '\\|')
        .replaceAll('\n', ' ')} |\n`
    }
  }
  output(
    `docs/diagrams/${type}.md`,
    `# ${titles[type]} diagrams\n\nVersion ${manifest.version}. The minimal spec below is validated and its complete React\nexample is compiled against the package tarball. See [API](../api/index.md) for\ndefaults, [React](../guides/react.md) for state/SSR and [Theming](../guides/theming.md)\nfor required host variables. For richer localized examples use the public examples entrypoint.\n\n\`\`\`json\n${json}\`\`\`\n${fields}\n## Boundaries\n\nIDs must be unique; references must exist. Parallel relations need explicit IDs\nwhen their identity must survive reordering. Large graphs and very long labels\nneed host-specific testing; there is no automatic text measurement or drag editor.\n`,
  )
}
const quick = usageSnippet('example-flowchart', 'flowchart', minimalSpecs.flowchart)
const intro = `# Getting started\n\nDocumentation for **${manifest.version}**. Install the matching publicly released\nversion, or use the candidate tarball supplied by a maintainer before publication.\nReact 18.3/19, ESM and Node 20.19+ are the supported target lines.\n\n## Installation\n\n\`\`\`bash\nnpm install @aesthc/diagram-lib@${manifest.version}\n\`\`\`\n\nUse your existing package manager; npm, pnpm, yarn and bun can install the same package.\nImport the stylesheet and define the host variables in [Theming](guides/theming.md).\nTailwind is not required.\n\n## First diagram\n\nThis complete example includes selection/focus state:\n\n\`\`\`tsx\n${quick}\`\`\`\n\n## Next steps\n\nFor Next App Router, add a client boundary as described in [React integration](guides/react.md).\nFor untrusted JSON, validate before rendering using the [API](api/index.md).\nAll seven examples are included in the package. A coding agent can start with\nthe [integration guide](agents/integrate.md), without installing extra tools.\n`
output('docs/getting-started.md', intro)
output(
  'site/src/generated/quick-start.ts',
  `// Generated by scripts/generate-docs.ts.\nexport const QUICK_START = ${JSON.stringify(quick)}\nexport const PACKAGE_VERSION = ${JSON.stringify(manifest.version)}\n`,
)
const publicRoot = 'https://alanslzrr.github.io/aesthc-diagram-lib/'
output(
  'README.md',
  `# @aesthc/diagram-lib\n\nSeven diagram types with one visual language: declarative React SVG diagrams with\nlocalized data, controlled interaction and host-defined themes.\n\n[Playground](${publicRoot}) · [Documentation](${publicRoot}docs/) · [Use with your agent](${publicRoot}agents/) · [MIT license](https://github.com/alanslzrr/aesthc-diagram-lib/blob/main/LICENSE)\n\n![Band diagram](https://raw.githubusercontent.com/alanslzrr/aesthc-diagram-lib/main/docs/diagrams/band.svg)\n\n## Install\n\n\`\`\`bash\nnpm install @aesthc/diagram-lib@${manifest.version}\n\`\`\`\n\nThis README targets ${manifest.version}; verify that the matching release is public.\nBefore initial publication, use the maintainer-provided candidate tarball rather\nthan assuming that a Git tag means npm is available. React 18.3/19, ESM, Node20.19+.\nTailwind is not required. Import the distributed CSS and configure [host theme variables](${publicRoot}docs/guides/theming/).\n\n## First diagram\n\n\`\`\`tsx\n${quick}\`\`\`\n\n## Diagram types\n\n${Object.entries(
    titles,
  )
    .map(([key, title]) => `- [${title}](${publicRoot}docs/diagrams/${key}/)`)
    .join(
      '\n',
    )}\n\nEach example has validated JSON, a complete React component and generated field\nreference. More detailed localized examples ship through the public examples import.\n\n## Use with your agent\n\nPass **${publicRoot}agents/** to your agent along with your task. The guide covers\ninstallation, public imports, styles, choosing a layout and verification. No skill,\nplugin or MCP server is required. To contribute to this repository instead, read\n[AGENTS.md](https://github.com/alanslzrr/aesthc-diagram-lib/blob/main/AGENTS.md).\n\n## API and limits\n\nSpecs → pure layouts → controlled SVG canvas. Registration is optional.\nRead the [API](${publicRoot}docs/api/), [React/SSR guide](${publicRoot}docs/guides/react/),\n[migration notes](${publicRoot}docs/guides/migration/) and [troubleshooting](${publicRoot}docs/guides/troubleshooting/).\n\nThis is not a drag editor or a solver for arbitrarily large graphs. External input\nneeds validation. Shared links are not encrypted; never include secrets. SVG/PNG\nexports and the JSON editor are playground features, not package APIs.\n\n## Development and support\n\nNode 22.14+ and pnpm 10.29.3. Run \`pnpm install --frozen-lockfile\`, then\n\`pnpm check\`. Browser checks require \`pnpm exec playwright install\`.\nSee [CONTRIBUTING.md](https://github.com/alanslzrr/aesthc-diagram-lib/blob/main/CONTRIBUTING.md),\n[SUPPORT.md](https://github.com/alanslzrr/aesthc-diagram-lib/blob/main/SUPPORT.md),\n[SECURITY.md](https://github.com/alanslzrr/aesthc-diagram-lib/blob/main/SECURITY.md) and\n[ROADMAP.md](https://github.com/alanslzrr/aesthc-diagram-lib/blob/main/ROADMAP.md).\n\nMaintained by [Alan Salazar](https://github.com/alanslzrr). MIT. Third-party font\nand icon notices are recorded in THIRD_PARTY_NOTICES.md.\n`,
)
console.log(
  check
    ? 'Examples, README and documentation are in sync'
    : 'Generated examples, README and documentation',
)
