import { readFileSync } from 'node:fs'
import { compareDocuments } from '/Users/alansalazar/development-projects/personal-proyects/aesthc-diagram-lib/src/graph/compare.ts'
import { verifyEvidence, declaredEvidence } from '/Users/alansalazar/development-projects/personal-proyects/aesthc-diagram-lib/src/editor-core/evidence.ts'
import { createLayoutProviderRegistry, runRegisteredLayout } from '/Users/alansalazar/development-projects/personal-proyects/aesthc-diagram-lib/src/editor-core/providers.ts'
const root='/Users/alansalazar/development-projects/personal-proyects/aesthc-diagram-lib';const seed=JSON.parse(readFileSync(root+'/tests/fixtures/editor/graph-document.json','utf8'))
async function main(){
for(const [name,mutate] of Object.entries({caption:(d:any)=>d.spec.caption='Changed title',metadata:(d:any)=>d.metadata.nodes.a={roles:['database'],tags:[],owner:'Changed owner'},groups:(d:any)=>d.scene.groups=[{id:'g',label:'New group',kind:'visual',nodeIds:['a'],locked:false}],views:(d:any)=>d.views=[{id:'v',label:'New view',focus:{nodeIds:['a'],edgeIds:[]}}]})){const after=structuredClone(seed);mutate(after);const r=compareDocuments(seed,after);console.log('compare '+name,r.ok&&{counts:r.value.counts,presentation:r.value.presentation,nodes:r.value.nodes,edges:r.value.edges})}
const evidence=structuredClone(seed);evidence.metadata.nodes.a={roles:[],tags:[],evidence:[{id:'e',repository:'https://github.com/example/repo',commit:'0123456789abcdef0123456789abcdef01234567',path:'src/main.ts',startLine:999999,endLine:1000000}]};let argument:any;const e=await verifyEvidence(evidence,{verify:async ref=>{argument=ref;return 'match'}});console.log('evidence declared valid',declaredEvidence(evidence).ok,'verifier argument',argument,'receipt status',e.ok&&e.value[0].status)
const d=structuredClone(seed);const registry=createLayoutProviderRegistry();registry.register({id:'mutator',run:async({document})=>{document.spec.caption='MUTATED BEFORE FAILURE';throw Error('provider failed')}});const r=await runRegisteredLayout(d,registry,'mutator',{expectedRevision:d.revision,latestRequestId:()=> 'r',requestId:'r'});console.log('provider rejection',r.ok&&r.value.status,'input caption',d.spec.caption)
const controller=new AbortController();controller.abort();let called=false,observedSignal:any;registry.register({id:'abort',run:async({document,signal})=>{called=true;observedSignal=signal.aborted;return {...document.scene,nodes:{}}}});const a=await runRegisteredLayout(structuredClone(seed),registry,'abort',{expectedRevision:seed.revision,latestRequestId:()=> 'a',requestId:'a',signal:controller.signal});console.log('pre-abort provider called',called,'provider signal aborted',observedSignal,'result',a.ok?a.value:a.diagnostics.map(d=>d.code))
}
main()
